# Generated by Django 3.1.7 on 2021-03-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0002_auto_20210323_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cc',
            field=models.CharField(max_length=7, null=True, verbose_name='Centro de custo'),
        ),
    ]
