# Generated by Django 3.1.7 on 2021-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0004_pessoa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(default='/media/usuarios/sem-foto.png', upload_to='usuarios', verbose_name='Foto'),
        ),
    ]
