# Generated by Django 3.1.7 on 2021-03-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0006_auto_20210324_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='matricula',
            field=models.CharField(max_length=6, unique=True, verbose_name='Matricula'),
        ),
    ]
