# Generated by Django 3.1.7 on 2021-03-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0008_pessoa_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True, verbose_name='Email'),
        ),
    ]
