# Generated by Django 3.1.7 on 2021-03-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0022_auto_20210331_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='ramal',
            field=models.CharField(default='Sem Ramal', max_length=4, null=True, verbose_name='Ramal'),
        ),
    ]
