# Generated by Django 3.1.7 on 2021-03-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0025_auto_20210331_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='ramal',
            field=models.CharField(default='Sem ramal', max_length=9, null=True, verbose_name='Ramal'),
        ),
    ]
