# Generated by Django 3.1.7 on 2021-04-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0026_auto_20210331_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=50, verbose_name='subtítulo')),
                ('noticia', models.TextField(verbose_name='Notícia')),
                ('imagem', models.ImageField(upload_to='fotoprincipal', verbose_name='Imagem')),
                ('anexo', models.FileField(null=True, upload_to='anexos', verbose_name='Anexo:')),
                ('datahora_edit', models.DateTimeField(null=True, verbose_name='datahora_aberto')),
            ],
        ),
    ]
