# Generated by Django 3.1.7 on 2021-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0027_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='datahora_edit',
        ),
        migrations.AddField(
            model_name='noticia',
            name='datahora',
            field=models.DateTimeField(null=True, verbose_name='datahora'),
        ),
    ]
