# Generated by Django 3.1.7 on 2021-04-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0028_auto_20210414_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aniversariante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('padrao', models.ImageField(default='aniversario/aniversariante.jpg', upload_to='aniversario', verbose_name='Foto')),
            ],
        ),
    ]
