# Generated by Django 3.1.7 on 2021-04-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0031_auto_20210420_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniversariante',
            name='padrao',
            field=models.ImageField(upload_to='aniversario', verbose_name='Foto'),
        ),
    ]
